#Configuration for robot odometry EKF#

frequency: 30

two_d_mode: true

publish_tf: true

odom_frame: odom
base_link_frame: base_link
world_frame: odom
map_frame: local

odom0: /zed/odom
odom0_config: [false, false, false,
               false, false, true,
               true, false, false,
               false, false, true,
               true, false, false]
odom0_differential: false

odom1: /odom
odom1_config: [true, true, false,
               false, false, true,
               true, false, false,
               false, false, true,
               true, false, false]
odom1_differential: false

imu0: /imu/data
imu0_config: [false, false, false,
              false, false, false,
              true, true, false,
              true, true, false,
              false, false, false]
imu0_differential: false


